<div class="login">
	<form id="formLogin" enctype="application/x-www-form-urlencoded" action="admin/auth/login" method="post">
	<table>
		<tr>
			<td>Username:</td>
			<td><input id="username" name="username" size="17" maxlength="16" tabindex="1" /></td>
			<td><input tabindex="3" type="submit" name="login" id="login" value="Sign in" /></td>
		</tr>
		<tr>
			<td>Password:</td>
			<td><input id="password" name="password" size="17" maxlength="16" type="password" tabindex="2" /></td>
		</tr>
		<tr>
			<td></td>
			<td><input type="checkbox" name="remember" id="remember"/> Remember me</td>
		</tr>
		<tr>
			<td><input type="hidden" name="target" value="" id="target" /></td>
		</tr>
	</table>
	</form>
</div>
	