<div class="tabMenu">
	<table class="tabMenu" cellspacing="0">
		<tr>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'design')   echo 'class="active"' ?> ><a href="admin/design/">Design</a></td>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'pages')   echo 'class="active"' ?> ><a href="admin/pages/">Pages</a></td>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'widgets')   echo 'class="active"' ?> ><a href="admin/widgets/">Widgets</a></td>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'profile')   echo 'class="active"' ?> ><a href="admin/profile/">Profile</a></td>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'password')   echo 'class="active"' ?> ><a href="admin/password/">Password</a></td>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'preferences')   echo 'class="active"' ?> ><a href="admin/preferences/">Preferences</a></td>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'sns')   echo 'class="active"' ?> ><a href="admin/sns/">Social Networks</a></td>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'advanced')   echo 'class="active"' ?> ><a href="admin/advanced/">Advanced</a></td>
			<td class="last">&nbsp;</td>
		</tr>
	</table>
</div>
		