<div class="tabMenu">
	<table class="tabMenu" cellspacing="0">
		<tr>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'share')   echo 'class="active"' ?> ><a href="admin/share/">Share</a></td>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'bookmarklet')   echo 'class="active"' ?> ><a href="admin/bookmarklet/">Bookmarklet</a></td>
			<td class="spacer">&nbsp;</td>
			<td <? if ($this->tab == 'backup')   echo 'class="active"' ?> ><a href="admin/backup/">Backup</a></td>
			<td class="last">&nbsp;</td>
		</tr>
	</table>
</div>
		