<?php $item 	= $this->item->toArray();
	  $username = $this->model->getProperty('username');
?>
 
<div class="delicious">
	<div  class="title entry-title p-name">Bookmarked the page <a href="<?= $item['link'] ?>" target="_blank"><?= $item['title'] ?></a></div>
	<?php if ($item['description']) : ?>
		<div class="note entry-content e-content"><?= strip_tags($item['description']); ?></div>
	<?php endif ?>
</div>