<form id="<?= $this->form->getName() ?>" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
	<table>
		<tbody>
			<tr>
				<td class='label'>
					Title:
				</td>
				<td class='element'>
					<?= $this->form->title ?>
				</td>
			</tr>
			<tr id='row_all' <?php if ($this->form->sources_filter->getValue()) : ?>style="display:none;"<?php endif ?>>
				<td class='label'>

				</td>
				<td class='element'>
					All data sources will be included in this page (<a href="#" onClick="onCustomize(); return false;">customize</a>)
				</td>
			</tr>
			<tr id='row_customize_sources' <?php if (!$this->form->sources_filter->getValue()) : ?>style="display:none;"<?php endif ?>>
				<td class='label'>

				</td>
				<td class='element'>					
					The following sources are included in this page: <br />
					<div id="sources_list">
						<?= $this->form->sources ?>
					</div>
				</td>
				<td class='element'>					
					The items of the following type are included in this page: <br />
					<div id="types_list">
						<?= $this->form->types ?>
					</div>
				</td>
			</tr>	
			<tr>
				<td class='label'>
				</td>
				<td class='element'>
					<?= $this->form->save ?>
					<?= $this->form->cancel ?>
				</td>
			</tr>
		</tbody>
	</table>	

	<?= $this->form->sources_filter ?>
	<?= $this->form->id ?>
	<?= $this->form->type ?>
</form>

<script type="text/javascript">
function onCustomize() {
	$('sources_filter').value = 1;
	$('row_all').hide();
	$('row_customize_sources').show();	
}
</script>
