<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<?= $this->headTitle() ?>
	<base href="<?= $this->base()->thisUrl(); ?>/" />
	<link href="style/story.css" media="screen, projection" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="style/lightbox.css" type="text/css" media="screen" />
	<?= $this->headLink() ?>	
	<?= $this->headScript() ?>
	<?= $this->headStyle() ?>
</head>
	
<body>

<div class="pagewrapper">
	<div class="<?= $this->section ?>" id="page">
		<?= $this->layout()->content ?>	
	</div>
</div>
	
<?php if ($this->footer) echo $this->footer; ?>

<script type="text/javascript" src="js/lightbox/lightbox.js"></script>

</body>
</html>