<h1>New users registration is temporarily closed</h1>

<p>
Due to the rapid increase in users we have had to close new registrations at Storytlr. We are now
working at scaling our infrastructure and will be adding new users progressively on a first come
first served basis. You can subscribe to our waiting list using the form below, we will send you an invite
as soon as possible.
</p>

<p>
If you already have an invite code, you can <a href="admin/register/register">register here</a>.
</p>

<div class="form_wrapper">
<?= $this->form ?>
</div>
