<div class="widget rsslink">
	<h2 class="title"><?= $this->title ?></h2>
	<div class="widget-content">
		<p>	
			<a href="rss/feed.xml" rel="alternate" type="application/rss+xml"><img src="images/rss.png" alt="" style="border: 0pt none ; vertical-align: middle;"></a>&nbsp;<a href="rss/feed.xml" rel="alternate" type="application/rss+xml">Subscribe in a reader</a>	
		</p>

<!--	<p>
			<a href="#" onclick="showDialog('customrss'); return false;">Build a custom feed</a>
		</p>
-->

	</div>
	<div class="clear"></div>
</div>