<?php 
	$comment = preg_replace("|([[:alpha:]]+://[^[:space:]]+[[:alnum:]/])|",'<a href="\\1" rel="nofollow">\\1</a>', $this->comment);  
	$comment = preg_replace("|@([a-zA-Z0-9\-]+\.[a-zA-Z0-9\-\.]+)|",'@<a href="http://\\1" target="_blank">\\1</a>',$comment);
	$comment = preg_replace("|@([a-zA-Z0-9\-\_]+)|",'@<a href="http://twitter.com/\\1" target="_blank">\\1</a>',$comment);
	$comment = preg_replace("|#([a-zA-Z0-9_]+)|",'<a href="tag/\\1">#\\1</a>',$comment); // add tag links	
?>
<div class='comment' id='comment_<?= $this->id ?>'>
	<div class='actions'>
	<?php if ($this->delete) : ?>
		<a class='delete' href='javascript:delete_comment(<?= $this->id ?>, <?= $this->source_id ?>, <?= $this->item_id ?>);' title="Delete comment"><img src="images/01.png" /></a>
	<?php endif ?>
	</div>
	<div class='avatar'>
		<img src='http://www.gravatar.com/avatar/<?= md5($this->email); ?>' alt="<?= $this->name; ?> Gravtar" />
	</div>
	<div class='header'>
		<div class='author'>
			<?php if (strlen($this->website)>0) : ?>
			  <a href="<?= $this->website ?>" rel="nofollow"><?= $this->name; ?></a> 
			<?php else : ?>
			  <?= $this->name; ?> 
			<?php endif ?>	
		</div>
		<div class='when'>
			<?= Stuffpress_Date::ago($this->when, "j M y \\a\\t G:i T"); ?>
		</div>
	</div>
	<div class='title'>
		<?= $comment ?>
	</div>	
</div>
