<?php 
	$comment = $this->entry;
	$comment = preg_replace("|([[:alpha:]]+://[^[:space:]]+[[:alnum:]/])|",'<a href="\\1" rel="nofollow">\\1</a>', $this->comment);  
	$comment = preg_replace("|@([a-zA-Z0-9\-]+\.[a-zA-Z0-9\-\.]+)|",'<a class="h-card" href="http://\\1" target="_blank">@<span class="p-name p-nickname">\\1</span></a>',$comment);
	$comment = preg_replace("|@([a-zA-Z0-9\-\_]+)|",'<a href="http://twitter.com/\\1" target="_blank">@<span class="p-name p-nickname">\\1</a></a>',$comment);
	$comment = preg_replace("|#([a-zA-Z0-9_]+)|",'<a href="tag/\\1">#\\1</a>',$comment); // add tag links	
?>
<div class='mention' id='mention_<?= $this->id ?>'>
	<div class='actions'>
	<?php if ($this->delete) : ?>
		<a class='delete' href='javascript:delete_mention(<?= $this->id ?>);' title="Delete mention"><img src="images/01.png" /></a>
	<?php endif ?>
	</div>
	<div class='avatar'>
                <?php if ($this->author_avatar != "") : ?>
		<img src='<?= $this->author_avatar; ?>' />
                <?php else : ?>
                <img src='images/book50.jpg' title='User has no avatar' />
                <?php endif ?>
	</div>
	<div class='header'>
		<div class='author'>
			<a href="<?= $this->author_url; ?>"><?= $this->author_name; ?></a>
		</div>
		<div class='when'>
			<a href="<?= $this->url?>"><?= Stuffpress_Date::ago($this->timestamp, "j M y \\a\\t G:i T"); ?></a>
		</div>
	</div>
	<div class='title'>
		<?= $comment ?>
	</div>
</div>
