<div class='mention' id='mention_<?= $this->id ?>'>
	<div class='actions'>
	<?php if ($this->delete) : ?>
		<a class='delete' href='javascript:delete_mention(<?= $this->id ?>);' title="Delete mention"><img src="images/01.png" /></a>
	<?php endif ?>
	</div>
	<div class='avatar'>
                <?php if ($this->author_avatar != "") : ?>
		<img src='<?= $this->author_avatar; ?>' />
                <?php else : ?>
                <img src='images/book50.jpg' title='User has no avatar' />
                <?php endif ?>
	</div>
	<div class='header'>
		<div class='author'>
			<a href="<?= $this->author_url; ?>"><?= $this->author_name; ?></a>
		</div>
		<div class='when'>
			<a href="<?= $this->url?>"><?= Stuffpress_Date::ago($this->timestamp, "j M y \\a\\t G:i T"); ?></a>
		</div>
	</div>
	<div class='title'>
		<?= $this->entry ?>
	</div>
</div>
