<h1>Configure</h1>
<p>
You can configure your homepage below.
</p>

<?= $this->partial("partials/tabmenu.phtml", array('tab' => 'advanced'));?>

<h3>Advanced settings</h3>
<p>
These settings are for experienced users who like to tweak or integrate Storytlr with their existing blog,
or with other social services. If you have any question, please refer to the faq or contact us at support@storytlr.com.
</p>
<img id = 'wait' src='images/wait30.gif' style='display:none;' />

<?= $this->form ?>
