<div class="widget bio">
	<h2 class="title"><?= $this->title ?></h2>
	<div class="widget-content">
		<div id="profile" class="vcard h-card">
			<div id="avatar">
				<?php if ($this->avatar) : ?>
				<img src="<?= $this->base()->thisUrl()?>/thumbnail/<?= $this->avatar ?>" alt="<?= $this->username ?>" class="photo u-photo" width="72" height="72" />
				<?php endif ?>
				<div id="name" class="fn p-name"><a href="<?= $this->base()->thisUrl()?>" class="u-url"><span class="given-name p-given-name"><?= $this->first_name?></span> <span class="family-name p-family-name"><?= $this->last_name?></span></a></div>
				<div id="location" class="adr p-adr"><?= $this->location ?></div>
			</div>
			<div id="details">
				<div id="bio p-note"><?= $this->bio ?></div>
			</div>
			<br class="fix" />
		</div>
	</div>
</div>
