<?php $type = $this->item->getType(); ?>


<?php if($type == 'image') : ?>
<div class="storytlr_image">
	<div  class="title">
		<?= $this->item->getTitle();?>
	</div>
	<div class="content">
		<a href="<?= $this->item->getImageUrl('large'); ?>" title="<?= $this->item->getTitle(); ?>" target="_blank"><img src="<?= $this->item->getImageUrl('medium'); ?>" width="350"></a>
	</div>
	<?php if ($this->item->getDescription()) : ?>
		<div class="note">
			<?= $this->item->getDescription(); ?>
		</div>
	<?php endif ?>
</div>
<?php elseif($type == 'audio') : ?>
<div class="storytlr_audio">
	<div  class="title">
		<?= $this->item->getTitle(); ?>
	</div>
	<div class="content">
		<object type="application/x-shockwave-flash" data="flash/player_mp3.swf" width="200" height="20">
		     <param name="movie" value="flash/player_mp3.swf" />
		     <param name="FlashVars" value="mp3=<?= $this->item->getAudioUrl(); ?>" />
		</object>
	</div>
	<?php if ($this->item->getDescription()) : ?>
		<div class="note">
			<?= $this->item->getDescription(); ?>
		</div>
	<?php endif ?>
</div>
<?php elseif($type == 'blog') : ?>
<div class="storytlr_blog">
	<div  class="title">
		<?= $this->item->getTitle(); ?> 
	</div>
	<div  class="content">
		<?= $this->item->getContent(); ?>
	</div>
</div>
<?php elseif($type == 'status') : ?>	
<div class="storytlr_status">
	<div  class="title">
		<?php 
			$title = 	preg_replace("|([[:alpha:]]+://[^[:space:]]+[[:alnum:]/])|",'<a href="\\1" target="_blank">\\1</a>',$this->item->getTitle());
			echo $title;
		?>
	</div>
</div>	
<?php elseif($type == 'link') : ?>	
<div class="storytlr_link">
	<div  class="title">
		Shared the link <a href="<?= $this->item->getLink(); ?>"><?= $this->item->getTitle(); ?></a>
	</div>
	<?php if ($this->item->getDescription()) : ?>
		<div class="note">
			<?= $this->item->getDescription(); ?>
		</div>
	<?php endif ?>
</div>
<?php elseif($type == 'video') : ?>
<div class="storytlr_video">
	<div class="content">
		<?= $this->item->getVideoPlayer(640, 480); ?>
	</div>
</div>
<?php endif ?>
