<li id="page_<?= $this->id ?>">
	<div style="height: 1%;">
		<div style="float:right;">
			<a href="#" onClick="onRemovePage(<?= $this->id ?>);return false;">Remove</a> | 
			<a href="admin/pages/edit/type/<?= $this->prefix ?>/id/<?= $this->id ?>" id='button_edit_page_<?= $this->id ?>'>Edit</a>
		</div>
		<img src="images/i-<?= $this->prefix ?>.png"/> <span id="page_<?= $this->prefix ?>_desc"><?= $this->title ?></span>
	</div>
</li>
