<h1>Configure</h1>
<p>
You can configure your homepage below.
</p>

<?= $this->partial("partials/tabmenu.phtml", array('tab' => 'avatar'));?>

<form id='formAvatar' enctype="multipart/form-data" action="admin/avatar/uploadimage" method="post">
<table>
	<tr>
		<td class="label"><label class="optional" for="link_color">Your avatar</label></td>
		<td>
			<?php if ($this->avatar) : ?>
				<img class="avatar" src="thumbnail/<?= $this->avatar ?>"/>
				<br />(<a href="admin/avatar/noavatar">Remove your avatar</a>)
				<br/><br/>
			<?php endif ?>	
			
			Upload a new avatar below:<br/> 
			<!-- MAX_FILE_SIZE must precede the file input field -->
				<input type="hidden" name="MAX_FILE_SIZE" value="2000000" 	style="display:none"/>
				<input type="hidden" name="image" 		  value="avatar" 	style="display:none"/>
				<!-- Name of input element determines name in $_FILES array -->
				<input name="file" type="file" /><input type="submit" value="Upload file"/><br />
				Image will be resized to 75x75 pixels. Maximum size is 2MB, only GIF, JPG and PNG are supported.
		</td>
	</tr>
</table>
</form>