<h1>How to use Storytlr with your own domain ?</h1>
<p>
You can setup storytlr to work with your own domain (e.g. www.johndoe.com) in such a way that
visitors to your site won't even notice that your page is being hosted by storytlr! Just follow
the instructions below and <a href='mailto:support@storytlr.com' subject="CNAME Issues">contact us</a> if you run into trouble. 
</p>
<ul>
	<li>Purchase a domain name and login into your DNS Host account</li>
	<li>Add a CNAME entry for the subdomain of your choice (e.g. www) and make it point to "storytlr.com". 
	Pay attention that some DNS Host require you to use Fully Qualified Names, in this case it should point towards
	"storytlr.com." (please note the dot at the end, this makes it a FQN).
	<li>In the Advanced configuration panel, add you personal domain name in the 'own domain' box (e.g. www.johndoe.com)</li>
	<li>Done! However your DNS changes may take up to 48 hours to propagate</li>
</ul>

<script src='http://storytlr.com/embed/story.js?id=225' type='text/javascript' /></script>
