<h1>Frequently asked questions</h1>
Got a question? Maybe we have an answer for you below.<br/><br/>

<h3>Questions and answers</h3>

<ol class="faqAnswers">
	<li><a title="1a" name="1a"></a><span>Can I use my own Cascading Style Sheet (CSS) ?</span><br/>
		Go to the <a href="admin/design/">Design configuration</a> and do your thing. Need more help check out <a href="page/css">Create your own style</a>.<br/><br/>
	</li>
	<li><a title="1b" name="1b"></a><span>Can I use Storytlr on my blog?</span><br/>
		We offer lifestream widgets, story widgets (see Tools menu) and you can also embed a story on your own blog (from your stories overview). Storytlr also offers different pages with blog functionality, so it may be worthwhile to start blogging on Storytlr itself.<br/><br/>
	</li>
	<li><a title="1f" name="1f"></a><span>How do I add disqus commenting to my storytlr site?</span><br/>
		If you have not got one, create an account on disqus. On disqus, add a website with the url http://username.storytlr.com (e.g. http://johndoe.storytlr.com), add a website name and shortname (e.g. johndoe). Then on Storytlr fill the shortname (e.g. johndoe) in the <a href="http://storytlr.com/admin/advanced/">Configure -> Advanced menu</a> in the Disqus commenting box. Save and the disqussion can start.<br/><br/>
	</li>
</ol>

<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/>
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
