<h1>Frequently asked questions</h1>
Got a question? Maybe we have an answer for you below.  Otherwise please add it to the feedback forum.<br/><br/>

<h3>Questions and answers</h3>

<ol class="faqAnswers">
	<li><a title="1a" name="1a"></a><span>Can I use my own Cascading Style Sheet (CSS) ?</span><br/>
		Go to the <a href="/admin/design/">Design configuration</a> and do your thing. Need more help check out <a href="/page/css">Create your own style</a>.<br/><br/>
	</li>
	<li><a title="1b" name="1b"></a><span>Can I use Storytlr on my own blog?</span><br/>
		We offer lifestream widgets, story widgets (see Tools menu) and you can also embed a story on your own blog (from your stories overview). Storytlr also offers different pages with blog functionality, so it may be worthwhile to start blogging on Storytlr itself.<br/><br/>
	</li>
	<li><a title="1e" name="1e"></a><span>How do I delete / cancel my account?</span><br/>
		<a href="mailto:support@storytlr.com">Send us an e-mail</a> with your username from the email address you used when registering. In the mail indicate that you want to have your account deleted. We'll process this as soon as possible. Please let us know what you're missing!<br/><br/>
	</li>
	<li><a title="1c" name="1c"></a><span>How do I use my own domain name with Storytlr?</span><br/>
		You can setup storytlr to work with your own domain (e.g. www.johndoe.com) in such a way that
		visitors to your site won't even notice that your page is being hosted by storytlr! Just follow
		the instructions below and <a href='mailto:support@storytlr.com' subject="CNAME Issues">contact us</a> if you run into trouble. 
		<br/><br/><ul>
			<li>Purchase a domain name and login into your DNS Host account</li>
			<li>Add a CNAME entry for the subdomain of your choice (e.g. www) and make it point to "storytlr.com". 
			Pay attention that some DNS Host require you to use Fully Qualified Names, in this case it should point towards
			"storytlr.com." (please note the dot at the end, this makes it a FQN).
			<li>In the Advanced configuration panel, add you personal domain name in the 'own domain' box (e.g. www.johndoe.com)</li>
			<li>Done! However your DNS changes may take up to 48 hours to propagate</li>
		</ul>
		<br/>
	</li>
	<li><a title="1d" name="1d"></a><span>How do I point several subdomains (e.g. http://www.mydomain.com and http://mydomain.com) to my storytlr site?</span><br/>
		This is a bug we're working on at the moment. You can however fix this by forwarding all subdomains (e.g. www.mydomain.com) to one (e.g. mydomain.com) in your DNS settings, and using a CNAME on the latter to Storytlr.<br/><br/>
	</li>
	<li><a title="1f" name="1f"></a><span>How do I add disqus commenting to my storytlr site?</span><br/>
		If you have not got one, create an account on disqus. On disqus, add a website with the url http://username.storytlr.com (e.g. http://johndoe.storytlr.com), add a website name and shortname (e.g. johndoe). Then on Storytlr fill the shortname (e.g. johndoe) in the <a href="http://storytlr.com/admin/advanced/">Configure -> Advanced menu</a> in the Disqus commenting box. Save and the disqussion can start.<br/><br/>
	</li>
	<li><a title="1g" name="1g"></a><span>Some sources are not updating, weren't these supposed to be realtime?</span><br/>
		We're using great technology developed by GNIP to update the following sources realtime: Delicious, Digg, Flickr, Twitter, Seesmic & YouTube. This is a complex and immature technology and sometimes it happens that updates are missed along the path. Therefore, we run an update script once a day (around 4AM CET) to collect all these missed items. The rest of the sources we poll at different intervals (maximum 3 hours). <br/><br/>
		As a rule of thumb: if your items did not show up after 24 hours, please ping us. <br/><br/>If you need something directly on your site, you can <a href="http://storytlr.com/admin/post/">post it directly via the Storytlr website</a> or you can <a href="http://storytlr.com/admin/bookmarklet/">use the bookmarklet</a>.
	</li>
</ol>

<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/>
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 
<br/> 