<h1>Getting started!</h1>
It's easy to setup your Storytlr page. You can either settle for the carefully crafted default settings or play with the extensive customization features.
<h2>Signing up</h2>
<p>
if you haven't done this already, first <a href="http://storytlr.com/admin/register">sign up</a> and confirm the e-mail. Then sign in above to get started.</p>

<h2>The basic setup</h2>
We strongly recommend to always go through the following steps:
<ol>
<li><a href="http://storytlr.com/admin/preferences/">Setting up your timezone</a> to avoid time-warps on imported items.</li>
<li><a href="http://storytlr.com/admin/services/">Import your existing web sources </a> to collect all your content scattered across the web.</li>
<li><a href="http://storytlr.com/admin/design/">Pick a design</a> you like. We have quite a few to choose from. Don't forget a good title for your site.</li>
<li><a href="http://storytlr.com/admin/pages/">Select the pages</a> you would like to see on your personal site.</li>
</ol>

Have a look at your site by clicking View in the top menu. If you like what you see, you're good to go. Otherwise consider the advanced options below.

<h2>The advanced setup</h2>
Just to highlight a few elements you may want to customize:
<ol>
<li>Keep your audience in the know and setup Storytlr to <a href="http://storytlr.com/admin/sns/">crosspost any source you want on Twitter</a>.</li>
<li>Let your visitors know who you are and <a href="http://storytlr.com/admin/profile/">add your details and avatar</a> to your page. Make sure to <a href="http://storytlr.com/admin/widgets/">include the profile / avatar widget</a>.</li>
<li>Setup Storytlr to <a href="http://storytlr.com/admin/advanced/">use your own domain</a>.</li>
<li><a href="http://storytlr.com/admin/widgets/">Change the widgets</a> displayed in the sidebar.</li>
<li>Go wild with your <a href="http://storytlr.com/admin/design/">own CSS</a>. We <a href="http://storytlr.com/page/css">offer some help</a> to get you started.</li>
<li><a href="http://storytlr.com/admin/advanced/">Setup Disqus commenting</a> to manage your comments.</li>
</ol>