<?php 
	$item = $this->item->toArray();  
	$title = $item['title'];
?>

<div class="soundcloud">
	<div  class="content-wrapper">
		<div  class="content">
			<?= $this->item->getDescription(); ?>
		</div>
	</div>
	<div  class="embed">
		If you don't see the video, watch it <a href="<?= $this->item->getLink(); ?>">here</a>.	
		<iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=http%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<?= $item["track_id"]; ?>&amp;color=ff6600&amp;auto_play=false&amp;show_artwork=true"></iframe>
	</div>
</div>