<?php if (count($this->links) > 0) : ?>
<div class="widget links">
	<h2 class="title"><?= $this->title ?></h2>
	<div class="widget-content">
		<ul>
		<?php foreach ($this->links as $link) : ?>
			<li>
				<a href="<?= $link['url']?>">
					<img src="images/<?= $link['prefix']?>.png" width='16' height='16' />
				</a>
				<a href="<?= $link['url']?>" rel="me">
					<?= $link['name']?>
				</a>
			</li>
		<?php endforeach ?>
		</ul>
	</div>
	<div class="clear"></div>
</div>
<?php endif ?>