<div class="qik">
	<div class="video">
		<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,115,0" width="640" height="480" id="qikPlayer" align="middle">
			<param name="allowScriptAccess" value="sameDomain" />
			<param name="allowFullScreen" value="true" />
			<param name="movie" value="http://qik.com/swfs/qikPlayer4.swf" />
			<param name="quality" value="high" />
			<param name="bgcolor" value="#333333" />
			<param name="FlashVars" value="rssURL=http://qik.com/video/<?= $this->item->getVideoID();?>.rss&autoPlay=true">
			<embed src="http://qik.com/swfs/qikPlayer4.swf" quality="high" bgcolor="#333333" width="640" height="480" name="qikPlayer" align="middle" allowScriptAccess="sameDomain" allowFullScreen="true" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" FlashVars="rssURL=http://qik.com/video/<?= $this->item->getVideoID(); ?>.rss&autoPlay=true"/>
		</object>	
	</div>
</div>