<?php $item 	= $this->item->toArray(); 
	  $video_id = $this->item->getVideoID();
	  $title  	= (strlen($item['title']) > 0) ? "({$item['title']})" : ""; 
?>

<div class="qik">
	<div  class="title">Live broadcast <?= $title?></div>

	<div id="container_qik_<?= $item['id'] ?>" class="video">
	
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="350" height="262" id="qikPlayer" align="middle">
		<param name="allowScriptAccess" value="sameDomain" />
		<param name="allowFullScreen" value="true" />
		<param name="movie" value="http://qik.com/swfs/qikPlayer4.swf" />
		<param name="quality" value="high" />
		<param name="bgcolor" value="#333333" />
		<param name="FlashVars" value="rssURL=http://qik.com/video/<?= $video_id ?>.rss&autoPlay=false">
		<embed src="http://qik.com/swfs/qikPlayer4.swf" quality="high" bgcolor="#333333" width="350" height="262" name="qikPlayer" align="middle" allowScriptAccess="sameDomain" allowFullScreen="true" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" FlashVars="rssURL=http://qik.com/video/<?= $video_id ?>.rss&autoPlay=false"/>
	</object>
	
	</div>
	
	<?php if ($this->item->getDescription()) : ?>
		<div class="note">
			<?= $this->item->getDescription(); ?>
		</div>
	<?php endif ?>
	
</div>