<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="nl" lang="nl">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<base href="<?= $this->base()->thisUrl() ?>/"/>
	<title>storytlr | your life online</title>
	<link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico" />	
	<link rel="stylesheet" href="style/style.css" type="text/css" media="screen" />
	<?= $this->headLink() ?>	
	<?= $this->headScript() ?>
	<?= $this->headStyle() ?>
</head>

<body onload="<?= $this->onload?>" >

<div id="pagewrapper" class="page_<?= $this->section ?>">
	
	<div class='overlay_status_wrapper' id='overlay_status_wrapper' style="display:none;">
		<div class='overlay_status'>
			<h5>Importing your data</h5>
			Depending on the number of items this can take a while.<br/><br/>
			<div class="progress"><img class="wait" src="images/ajax-loader.gif" /> Importing...</div>
		</div>
	</div>
	
	<div id="header">
		<div id="home"><a href="admin/home" onfocus="this.blur();" title="Homepage">&nbsp;</a></div>
		<div id="headerimg">
			
			<div id="loginStatus">
				<?php if ($this->application()->authenticated()) : ?>
					<span class="signedin">Signed in as <strong><?= $this->application()->username() ?></strong></span> <a href='admin/auth/logout' 	title='Sign out' 	onfocus='this.blur()' <?php if ($this->section == "logout") {?> class="current" <?php }?>>Sign out</a>	
				<?php else : ?>
					<?= $this->partial("partials/login.phtml");?>
				<?php endif ?>
			</div>
			
		</div>
	</div>
	
	<?php if (!$this->application()->authenticated()) : ?>
	<!--  <div id="banner">
		Want to support us ? Then vote for us at the <a href="http://uk.techcrunch.com/2009/06/24/the-europas-best-bootstrapped-startup-less-than-3-years-old/">Techcrunch Europas</a> award. Thanks ! 
	</div>
	-->
	<?php endif ?>
	
	<?php if ($this->application()->authenticated()) : ?>
	<div id="navigationMenu">
		<ul>
			<li><a href='admin/post/'	 					title='Post'		onfocus='this.blur()' <?php if ($this->section == "post") {?> class="current" <?php }?>>Post</a></li>
			<li><a href='admin/services/' 					title='Import'	 	onfocus='this.blur()' <?php if ($this->section == "services") {?> class="current" <?php }?>>Sources</a></li>											
			<li><a href='admin/story/' 						title='Storytell'	onfocus='this.blur()' <?php if ($this->section == "story") {?> class="current" <?php }?>>Storytell</a></li>		
			<li><a href='admin/share/' 						title='Tools' 		onfocus='this.blur()' <?php if ($this->section == "tools") {?> class="current" <?php }?>>Tools</a></li>
			<li><a href='admin/design/' 					title='Configure' 	onfocus='this.blur()' <?php if ($this->section == "config") {?> class="current" <?php }?>>Configure</a></li>
			<li><a href='http://<?= $this->base()->myDomain(false) ?>' 		title='View' 		onfocus='this.blur()'>View</a></li>										
		</ul>
	</div>
	<?php else : ?>
	<div id="navigationMenu">
		<ul class="logout">	
		</ul>
	</div>
	<?php endif ?>
		
	<div id="contentwrapper">
		
		<div id="page">
		
			<div id="status_messages">
				<?php if ($this->status_messages) : ?>
				<ul>
					<?php foreach ($this->status_messages as $message) echo "<li>$message</li>\r\n" ?>
				</ul>
				<?php endif ?>
			</div>
			
			<div id="error_messages">
				<?php if ($this->error_messages) : ?>
				<ul>
					<?php foreach ($this->error_messages as $message) echo "<li>$message</li>\r\n" ?>
				</ul>
				<?php endif ?>
			</div>
		
			<div id="content" class="narrowcolumn">
				<?= $this->layout()->content ?>
			</div>
		
		</div>
		
	</div>
	
	<br class="fix" />
	
	<div id="footer">
		
		<div class="blockwrapper">
			<div class="block">
				<h2>Legal stuff</h2>
				You are running storytlr version <?php echo STORYTLR_VERSION ?>, available under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License version 2.0</a>.
			</div>
				
			<div class="block">
				<h2>About us</h2>
				Find out more about storytlr below. 
				<ul>
					<li><a href="http://storytlr.googlecode.com">The storytlr initiative</a></li>
				</ul>
			</div>
			
			<div class="block">
				<h2>Need help?</h2>
				Got a question, a problem or a great idea: let us know!
				<ul>
					<li><a href="http://code.google.com/p/storytlr/wiki/GetStarted">Getting started!</a></li>
					<li><a href="http://code.google.com/p/storytlr/wiki/WikiHome">Storytlr Wiki</a></li>
					<li><a href="http://groups.google.com/group/storytlr-discuss">Mailing list</a></li>
				</ul>
				
			</div>
			
			<div class="block">
				<h2>Contact us</h2>
				Send us an email in case you want to learn more.
				<ul>
					<li><a href="mailto:info@storytlr.com">Email us</a></li>
					<li><a href="http://twitter.com/storytlr">Follow us on twitter</a></li>
				</ul>
			</div>	
		</div>
		
		<br class="fix" />
		
		<div id="copyright">
		<p>
			Web site powered by <a href="http://storytlr.googlecode.com">storytlr</a>, version <?php echo STORYTLR_VERSION ?>, available under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License version 2.0</a>.
		</p>
		</div>
	</div>

</div>

</body>

</html>		
	